### PR TITLE
Fix "The signature in the decrypted message is invalid" -  pybitmessage use sha256 for signature

### PR DESCRIPTION
**Pull request by yshurik**
Symptoms:

```
[2021-10-27T11:58:21Z] Successfully decrypted a message using the key “[chan] bitmessage”
[2021-10-27T11:58:21Z] The signature in the decrypted message is invalid
```
We can see that message is delivered, decrypted ok, but failed on signature, so not come to mailbox.
Mostly seen on messages coming from channels. Looks like depend on version PyBitmessage is using sha256 for digest to make signature.

PyBitmessage appropriate codes:

```
def verify(msg, sig, hexPubkey):
    """Verifies with hex public key using SHA1 or SHA256"""
    # As mentioned above, we must upgrade gracefully to use SHA256. So
    # let us check the signature using both SHA1 and SHA256 and if one
    # of them passes then we will be satisfied. Eventually this can
    # be simplified and we'll only check with SHA256.
    try:
        # old SHA1 algorithm.
        sigVerifyPassed = makePubCryptor(hexPubkey).verify(
            sig, msg, digest_alg=OpenSSL.digest_ecdsa_sha1)
    except:
        sigVerifyPassed = False
    if sigVerifyPassed:
        # The signature check passed using SHA1
        return True
    # The signature check using SHA1 failed. Let us try it with SHA256.
    try:
        return makePubCryptor(hexPubkey).verify(
            sig, msg, digest_alg=OpenSSL.EVP_sha256)
    except:
        return False
```

We can see it uses sha256 as fallback when sha1 not passed.

notbit current codes:

```
static void
check_signature_in_decrypted_msg(const uint8_t *header,
                                 size_t header_size,
                                 struct ntb_crypto_cookie *cookie)
{
        struct ntb_proto_decrypted_msg msg;
        uint8_t digest[SHA_DIGEST_LENGTH];
        SHA_CTX sha_ctx;

        ntb_log("Successfully decrypted a message using the key “%s”",
                cookie->decrypt_msg.chosen_key->label);

        if (!ntb_proto_get_decrypted_msg(cookie->decrypt_msg.result->data,
                                         cookie->decrypt_msg.result->size,
                                         &msg)) {
                ntb_log("The decrypted message is invalid");
                goto invalid;
        }

        SHA1_Init(&sha_ctx);
        SHA1_Update(&sha_ctx,
                    header + sizeof (uint64_t),
                    header_size - sizeof (uint64_t));
        SHA1_Update(&sha_ctx,
                    cookie->decrypt_msg.result->data,
                    msg.signed_data_length);
        SHA1_Final(digest, &sha_ctx);

        if (!check_signature_for_digest(cookie->crypto,
                                        msg.sender_signing_key,
                                        digest,
                                        msg.sig,
                                        msg.sig_length)) {
                ntb_log("The signature in the decrypted message is invalid");
                goto invalid;
        }

        return;

invalid:
        ntb_key_unref(cookie->decrypt_msg.chosen_key);
        cookie->decrypt_msg.chosen_key = NULL;
        ntb_blob_unref(cookie->decrypt_msg.result);
        cookie->decrypt_msg.result = NULL;
}
```

So we see that fallback of sha256 is needed.

Solution: this merge requests to check sha256 is sha1 not passed.

Tested: messages sent from PyBitmessage to "notbit" channel are coming to notbit okay after the change:

```
[2021-10-27T21:22:34Z] Successfully decrypted a message using the key “[chan] notbit”
[2021-10-27T21:22:34Z] Accepted message from BM-2cXALKb732bwuVKjSk1AEtsXbHyaqEXNoJ
[2021-10-27T21:22:34Z] The decrypted message contains no acknowledgement data
[2021-10-27T21:22:34Z] Saving message
```

### CODE REVIEW

**Comment by yshurik** [comment]
@bpeel any chance to check and merge?

**Comment by bpeel** [comment]
Thanks for the merge request. I think the idea looks good but it might but nice to clean up the code to avoid duplicating the parts that generate the digest. What do you think about replacing all the calls to `SHA1_*` with the equivalent `EVP_Digest*` functions? That way the code that generates the digest could be moved to a helper function that takes the hashing algorithm as a parameter so the same code could be used for both SHA1 and SHA256.

Do we need to do the same thing for `check_signature_for_data`? As far as I can tell from a quick look at the PyBitmessage code it uses the same code to sign keys as well as the messages, so eventually new keys will be generated using SHA256, right? `check_for_signature_for_data` is used for checking the signature on the key.

Please also try to keep to the coding style and use `/* C-style */` comments instead of `// C++`.

**Comment by g1itch** [comment]
> so eventually new keys will be generated using SHA256, right?

Sorry to interfere your discussion... As far as I know bitmessage uses SHA512 for keys, and there are no plans to change that. Maybe Peter will clarify this question, if you ask him.

Another question I have regarding the SHA256 signatures is about https://github.com/antorunexe/notbit: do you think that implementation is bad? I'm not a C/C++ coder, unfortunately );

Good to see you're still in business. I counted this project asleep at  least, if not dead at all (;

**Comment by yshurik** [comment]
I changed the code to use ```EVP_Digest*()``` calls and collected them in ```static compute_msg_digest()```. Changed comment style too. 

I see ```check_signature_for_data()``` is used only in ```handle_check_unencrypted_pubkey()```, and I think you are right about signing keys digests as sha256 in pybitmessage. Though I haven't seen yet messages ```"The signature in the pubkey message is invalid"``` in the log. 

But I can adjust ```check_signature_for_data()``` too. Please let me know if first part with ```EVP_Digest*()``` is fine.

**Comment by bpeel** [comment]
Thanks for updating the branch. I’ve squashed all the commits into one and merged it. I’ve also added another patch to make it try the algorithms in a loop instead of the chain of if-statements in order to make it a bit more manageable.

Feel free to make a second MR to fix `handle_check_unencrypted_pubkey` too if you find the time. You can cause that log message if you set `digestalg = sha256` in `keys.dat` in PyBitmessage, generate a new address and then use it to send a message to notbit.

**Pull request closed without merging**
